name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.sha }}
          name: Release ${{ github.sha }}
          draft: false
          prerelease: false
          generate_release_notes: true

  build:
    runs-on: ubuntu-latest
    needs: create_release
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Arduino CLI
        uses: actions/cache@v3
        with:
          path: |
            ~/.arduino15
            ~/Arduino
          key: ${{ runner.os }}-arduino-${{ hashFiles('**/Firmware/sms-stm32/sms-stm32.ino') }}

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Install STM32 core and required libraries
        run: |
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core install STMicroelectronics:stm32
          arduino-cli lib install "DHT sensor library"
          arduino-cli lib install "OneWire"
          arduino-cli lib install "DallasTemperature"

      - name: Compile Firmware
        run: |
          cd Firmware/sms-stm32
          arduino-cli compile --fqbn STMicroelectronics:stm32:GenF1:pnum=BLUEPILL_F103C8 --verbose sms-stm32.ino
          mkdir -p ../../release-files
          cp build/STMicroelectronics.stm32.GenF1/sms-stm32.ino.bin ../../release-files/sms-stm32-bluepill.bin

      - name: Upload Release Assets
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.sha }}
          files: |
            release-files/sms-stm32-bluepill.bin

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: release-files/sms-stm32-bluepill.bin
          if-no-files-found: error
